---
version: '3.5'
services:
  app:
    build: .
    command: "elixir --erl '-setcookie COOKIE -name phoenix@127.0.0.1' -S /usr/local/bin/mix phx.server"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phoenix.entrypoints=http"
      - "traefik.http.routers.phoenix.rule=Host(`phoenix-app.dev.localhost`)"
      - "traefik.http.routers.phoenix.middlewares=https-redirect@file"
      - "traefik.http.routers.phoenix-secure.entrypoints=https"
      - "traefik.http.routers.phoenix-secure.rule=Host(`phoenix-app.dev.localhost`)"
      - "traefik.http.routers.phoenix-secure.tls=true"
      - "traefik.http.services.phoenix.loadbalancer.server.port=4000"
      - "traefik.docker.network=traefik"

  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phoenix_api_dev

networks:
  default:
    name: docker-phoenix